name: GitHub Security Alerts for Jira

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.1.0
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GitHubSecurityToken }}
          JIRA_TOKEN: ${{ secrets.JiraApiToken }}
          JIRA_HOST: https://catalystsoftware.atlassian.net/
          JIRA_USER: francis@getcatalyst.io
          JIRA_PROJECT: CAT
          JIRA_ISSUE_TYPE: Security & Vulnerabilities
          JIRA_RESTRICTED_GROUP: Developers
          JIRA_RESTRICTED_COMMENT_ROLE: Contributors
